name: Build GH Page

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'otterdog/*.jsonnet'
      - 'otterdog/*.json'
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/build-page.yml'

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate-markdown:
    # do not run the workflow in the template repo itself
    if: ${{ !contains (github.repository, '/.eclipsefdn-template') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout OtterDog
        run: git clone https://gitlab.eclipse.org/eclipsefdn/security/otterdog.git

      - name: Checkout EclipseFdn/otterdog-configs
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: EclipseFdn/otterdog-configs
          path: otterdog-configs

      # checkout the HEAD ref
      - name: Checkout HEAD
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: ${{ github.repository_owner }}

      - name: Install jsonnet-bundler
        run: |
          go install -a github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@v0.5.1
          echo $(go env GOPATH)/bin >> $GITHUB_PATH

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Install dependencies with poetry
        run: |
          poetry install --only=main
        working-directory: otterdog

      - name: Copy configuration from HEAD ref
        run: |
          mkdir -p orgs/${{ github.repository_owner }}
          cp -r ../${{ github.repository_owner }}/otterdog/* orgs/${{ github.repository_owner }}
        working-directory: otterdog-configs

      - name: Generate current configuration as markdown
        run: ../otterdog/otterdog.sh show ${{ github.repository_owner }} -c otterdog.json --markdown --output-dir generated-site
        working-directory: otterdog-configs

      - name: Generate default configuration as markdown
        run: ../otterdog/otterdog.sh show-default ${{ github.repository_owner }} -c otterdog.json --markdown > default.txt
        working-directory: otterdog-configs

      - name: Upload generated site content
        uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6 # v4.2.0
        with:
          name: generated-site
          path: |
            otterdog-configs/default.txt
            otterdog-configs/orgs/${{ github.repository_owner }}/vendor/otterdog-defaults/*.libsonnet
            otterdog-configs/generated-site/

  build-page:
    runs-on: ubuntu-latest
    needs: generate-markdown
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Download generated site content
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
        with:
          name: generated-site
      - shell: bash
        run: |
          cat default.txt >> ./docs/playground.md
          cp generated-site/*.md ./docs/
          cp orgs/${{ github.repository_owner }}/vendor/otterdog-defaults/*.libsonnet ./docs/jsonnet/
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: 3.x
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Build with Mkdocs
        run: mkdocs build
      - name: Setup Pages
        uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d # v4.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@0252fc4ba7626f0298f0cf00902a25c6afc77fa8 # v3.0.0

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-page
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@87c3283f01cd6fe19a0ab93a23b2f6fcba5a8e42 # v4.0.3
